# Generated by Django 6.1 on 2026-08-29 15:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageQR',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('qr_image', models.ImageField(blank=True, upload_to='qrcodes/')),
                ('package', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qr', to='accounts.package')),
            ],
        ),
    ]
