# Generated by Django 6.1 on 2026-09-05 08:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_packageqr'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={},
        ),
        migrations.CreateModel(
            name='Disposal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item', models.CharField(choices=[('mobile', 'Mobile Phone'), ('laptop', 'Laptop'), ('battery', 'Battery'), ('plastic', 'Plastic Bottle')], max_length=50)),
                ('instruction', models.TextField()),
                ('disposed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disposals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
