# Generated by Django 6.1 on 2026-09-09 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_company_options_disposal'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='disposal',
            name='instruction',
        ),
        migrations.AddField(
            model_name='disposal',
            name='collection_center_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='disposal',
            name='disposal_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='disposal',
            name='instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='disposal',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('received', 'Received'), ('recycled', 'Recycled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='disposal',
            name='item',
            field=models.CharField(choices=[('mobile', 'Mobile Phone'), ('laptop', 'Laptop'), ('battery', 'Battery'), ('charger', 'Charging Cable'), ('earphones', 'Earphones'), ('keyboard', 'Keyboard'), ('mouse', 'Mouse'), ('monitor', 'Monitor'), ('printer', 'Printer'), ('television', 'Television'), ('usb', 'USB Drive'), ('powerbank', 'Power Bank')], max_length=50),
        ),
    ]
