# Generated by Django 6.1 on 2026-09-21 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_collectioncenter_remove_disposal_instruction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EcoBagOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('seed_type', models.CharField(max_length=100)),
                ('batch_code', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(default='pending', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.company')),
            ],
        ),
    ]
