async function verifyProductImages({
  firstProductImage,
  userProductIdImage,
  secondProductImage,
  centreProductIdImage,
  idImage,
  expectedProduct = {},
  captureMetadata
}) {
  try {
    const GEMINI_API_KEY = process.env.GEMINI_API_KEY;
    if (!GEMINI_API_KEY) {
      throw new Error('GEMINI_API_KEY is not set in environment variables.');
    }
    const CANDIDATE_MODELS = [
      'gemini-flash-lite-latest',
      'gemini-3.5-flash-lite',
      'gemini-3.8-flash',
      'gemini-flash-latest'
    ];

    // Helper functions to parse base64 and mime type from data URIs
    const getBase64Data = (dataUrl) => {
      if (!dataUrl || typeof dataUrl !== 'string') return null;
      const parts = dataUrl.split(',');
      return parts.length === 2 ? parts[1] : null;
    };

    const getMimeType = (dataUrl) => {
      if (!dataUrl || typeof dataUrl !== 'string') return 'image/jpeg';
      const match = dataUrl.match(/^data:(image\/[a-zA-Z0-9\-\+]+);base64,/);
      return match ? match[1] : 'image/jpeg';
    };

    // Gather and label all available evidence images
    const imageParts = [];
    const addImagePart = (label, dataUri) => {
      const data = getBase64Data(dataUri);
      if (data) {
        const mime = getMimeType(dataUri);
        imageParts.push({ text: `=== ${label} ===` });
        imageParts.push({ inlineData: { mimeType: mime, data } });
      }
    };

    addImagePart('Citizen Image 1: Main / Front Product Photo', firstProductImage);
    addImagePart('Citizen Image 2: Serial Label / Back / ID Photo', userProductIdImage || idImage);
    addImagePart('Collection Centre Image 1: Live Main / Front Photo', secondProductImage);
    addImagePart('Collection Centre Image 2: Live Serial Label / Back Photo', centreProductIdImage || idImage);

    if (imageParts.length === 0) {
      return {
        available: true,
        approved: false,
        decision: 'REJECTED',
        confidence: 0,
        score: 0,
        score_breakdown: { no_images: 0 },
        checks: { images_present: false },
        explanation: 'No valid image data was provided for verification.'
      };
    }

    const expectedCategory = expectedProduct.category || expectedProduct.item_name || 'Electronics';
    const expectedBrand = expectedProduct.brand || expectedProduct.brand_name || 'Generic/Any';
    const expectedSerial = expectedProduct.serial_number || 'N/A';

    const systemPrompt = `You are a forensic Anti-Fraud & Hardware Verification Officer for the EcoHub national e-waste recycling grid.
Your task is to inspect the submitted images to verify that a REAL, PHYSICAL electronic device is being disposed of, and strictly REJECT any fraud, spoofing, screen replays, AI images, or mismatches.

EXPECTED PRODUCT DECLARED BY CITIZEN:
- Category: "${expectedCategory}"
- Item Name: "${expectedProduct.item_name || expectedCategory}"
- Brand: "${expectedBrand}"
- Declared Serial Number: "${expectedSerial}"

YOU MUST ENFORCE THESE 5 STRICT FORENSIC RULES:

1. ANTI-SCREEN-REPLAY / SPOOFING DETECTION (CRITICAL):
   - Check if someone is pointing their camera at ANOTHER smartphone screen, computer monitor, tablet, or TV display showing a picture of an item (Screen-in-Screen fraud).
   - Look for visual signs of a digital screen:
     * Outer bezels, notches, or borders of another displaying smartphone/tablet.
     * Moiré interference patterns, scanlines, pixel grids, or LED/OLED subpixel matrix.
     * Screen glare, display backlight reflection, or flat glass surface reflections.
     * On-screen digital UI elements (status bar, battery icon, time, image viewer borders, gallery icons).
   - If ANY photo is a photo of a screen or digital display, you MUST IMMEDIATELY REJECT with is_screen_recap = true, is_live_physical_object = false, confidence_score = 0, and decision = "REJECT".

2. ANTI-AI GENERATED & SYNTHETIC IMAGE CHECK (CRITICAL):
   - Check if any image is generated by an AI model (e.g. Midjourney, DALL-E, Stable Diffusion, Flux), a 3D digital render, or a stock photo.
   - Look for uncanny plastic textures, hallucinated/gibberish label text, unrealistic physics, unnatural lighting, or missing real-world micro-details.
   - If AI-generated or synthetic, you MUST IMMEDIATELY REJECT with is_ai_generated = true, confidence_score = 0, and decision = "REJECT".

3. REAL PHYSICAL ELECTRONIC DEVICE REQUIREMENT:
   - The object MUST BE a genuine, physical electronic/electrical hardware device or component (e.g. smartphone, laptop, PC, circuit board, monitor, tablet, battery, charger, cable, printer, television, appliance).
   - The device must be resting in a real physical environment (desk, table, hand, floor, counter) with natural depth, realistic shadows, and ambient room light.
   - If the photo shows a human face/selfie, animal, food, clothing, paper, furniture, empty room, scenery, shoes, bottle, book, or non-electronic item, REJECT with is_electronic_item = false and confidence_score = 0.

4. ACCURATE TWO-PARTY PRODUCT MATCHING (Citizen vs Collection Centre):
   - Compare the photos submitted by the Citizen against the live photos captured by the Collection Centre officer.
   - Verify that both parties photographed the EXACT SAME physical hardware unit (matching brand, color, form-factor, ports, wear/scratches, screen condition, and serial labels).
   - ACCOUNT FOR CAMERA ORIENTATION & ANGLE: The photos may be taken from different angles (one portrait/vertical and one landscape/horizontal, rotated 90°/180°, or closer/further). Mentally rotate and compare the underlying physical features. Do NOT reject solely for rotation or angle if the physical device is identical.
   - If the Collection Centre photographed a completely different device, mark physical_object_match = false and REJECT.

5. HARDWARE CATEGORY & SPECIFICATION ALIGNMENT:
   - Verify that the photographed device matches the declared category "${expectedCategory}". (e.g. If declared "Laptop" but photo is a "Mobile Phone", flag category mismatch).

Return ONLY a valid JSON object matching this schema:
{
  "is_electronic_item": boolean,
  "is_live_physical_object": boolean,
  "is_screen_recap": boolean,
  "is_ai_generated": boolean,
  "detected_device_type": string,
  "detected_brand": string,
  "category_match": boolean,
  "physical_object_match": boolean,
  "lighting_angle_issue": boolean,
  "front_back_consistency": boolean,
  "confidence_score": number (0 to 100),
  "decision": "ACCEPT" | "REVIEW_REQUIRED" | "REJECT",
  "audit_notes": string (concise explanation of why it was accepted, placed under review, or rejected),
  "guidance_message": string (actionable advice to collection centre officer, e.g. 'Retake photo with less glare', 'Check declared category', 'Real object confirmed'),
  "failed_reasons": string[] (list of reasons if failed, empty array if passed)
}`;

    const parts = [
      { text: systemPrompt },
      ...imageParts
    ];

    let result = null;
    let lastError = null;

    for (const model of CANDIDATE_MODELS) {
      try {
        const url = `https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${GEMINI_API_KEY}`;
        const response = await fetch(url, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            contents: [{ parts }],
            generationConfig: {
              responseMimeType: "application/json",
              temperature: 0.1
            }
          }),
          signal: AbortSignal.timeout(25000)
        });

        if (response.ok) {
          result = await response.json();
          if (result.candidates?.[0]?.content?.parts?.[0]?.text) {
            break;
          }
        } else {
          const errText = await response.text().catch(() => '');
          lastError = new Error(`[${model}] HTTP ${response.status}: ${errText.slice(0, 150)}`);
        }
      } catch (err) {
        lastError = err;
      }
    }

    if (!result) {
      throw lastError || new Error('All Gemini candidate models failed to return a response.');
    }

    const textContent = result.candidates[0].content.parts[0].text;
    const parsed = JSON.parse(textContent);

    const score = typeof parsed.confidence_score === 'number' ? Math.max(0, Math.min(100, Math.round(parsed.confidence_score))) : 0;
    const isElectronic = parsed.is_electronic_item === true;
    const isRealPhysical = parsed.is_live_physical_object !== false && parsed.is_screen_recap !== true && parsed.is_ai_generated !== true;
    const isObjectMatch = parsed.physical_object_match !== false;
    const isCategoryMatch = parsed.category_match !== false;
    const hasLightingAngleIssue = parsed.lighting_angle_issue === true;
    
    // Strict acceptance criteria: Must be real physical electronic hardware, not a screen photo, not AI, matching object
    const isAccept = parsed.decision === "ACCEPT" && isElectronic && isRealPhysical && isObjectMatch && score >= 75;

    let finalDecision = 'REJECTED';
    if (isAccept) {
      finalDecision = score >= 80 ? 'VERIFIED' : 'REVIEW_REQUIRED';
    } else if (score >= 50 && isElectronic && isRealPhysical) {
      finalDecision = 'REVIEW_REQUIRED';
    } else if (hasLightingAngleIssue && isElectronic) {
      finalDecision = 'REVIEW_REQUIRED';
    }

    // Build guidance message
    let guidance = parsed.guidance_message || '';
    if (!guidance) {
      if (hasLightingAngleIssue) {
        guidance = 'Lighting or camera angle issue detected. Please retake the photo in better ambient light without glare.';
      } else if (!isCategoryMatch && isObjectMatch) {
        guidance = `Category mismatch: Citizen declared '${expectedCategory}' but detected item is '${parsed.detected_device_type || 'different hardware'}'.`;
      } else if (!isRealPhysical) {
        guidance = 'Anti-spoofing alert: Screen photo or AI-generated image detected. Please present the physical device.';
      } else if (!isElectronic) {
        guidance = 'Non-electronic item: Only electronic hardware and e-waste can be verified.';
      } else if (finalDecision === 'VERIFIED') {
        guidance = 'Physical hardware verified successfully.';
      }
    }

    return {
      available: true,
      approved: isAccept && finalDecision === 'VERIFIED',
      decision: finalDecision,
      confidence: score / 100,
      score: score,
      score_breakdown: {
        ai_confidence: score,
        is_electronic_item: isElectronic ? 100 : 0,
        is_real_physical_object: isRealPhysical ? 100 : 0,
        physical_object_match: isObjectMatch ? 100 : 0,
        category_match: isCategoryMatch ? 100 : 0
      },
      checks: {
        is_electronic_item: isElectronic,
        is_real_physical_object: isRealPhysical,
        is_screen_recap: parsed.is_screen_recap === true,
        is_ai_generated: parsed.is_ai_generated === true,
        physical_object_match: isObjectMatch,
        category_match: isCategoryMatch,
        lighting_angle_issue: hasLightingAngleIssue,
        front_back_consistency: parsed.front_back_consistency ?? true,
        ai_fraud_check_passed: isAccept
      },
      explanation: parsed.audit_notes || (isRealPhysical ? (isElectronic ? 'Inspection complete.' : 'Image rejected: Not an electronic device.') : 'Image rejected: Fake/Screen/AI image detected.'),
      guidance_message: guidance,
      details: {
        detected_device_type: parsed.detected_device_type || 'Unknown',
        detected_brand: parsed.detected_brand || 'Unknown',
        failed_reasons: parsed.failed_reasons || []
      }
    };

  } catch (error) {
    console.error('Gemini AI Verification Error:', error?.message || error);

    return {
      available: false,
      approved: false,
      decision: 'ERROR',
      confidence: 0,
      score: 0,
      score_breakdown: { error: 0 },
      checks: { api_reachable: false },
      explanation: `AI verification failed: ${error?.message || 'Unknown error'}. Please verify your Gemini API connection.`
    };
  }
}

module.exports = { verifyProductImages };